#!/usr/bin/env python3
"""Generate topics_l1.csv and topics_l2.csv for blog SEO taxonomy."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

# (code, slug, name_ko, mega_group)
L1_LIST = [
    ("01", "daily-life", "일상·에세이", "라이프"),
    ("02", "self-improvement", "자기계발·습관", "라이프"),
    ("03", "productivity", "생산성·도구", "라이프"),
    ("04", "minimal-organize", "미니멀·정리·수납", "라이프"),
    ("05", "relationships", "인간관계·소통", "라이프"),
    ("06", "dating", "연애·썸", "라이프"),
    ("07", "wedding", "결혼·웨딩", "라이프"),
    ("08", "single-divorce", "이혼·재혼·싱글", "라이프"),
    ("09", "saving-money", "재테크·절약", "머니"),
    ("10", "investing", "투자·주식", "머니"),
    ("11", "real-estate", "부동산·청약", "머니"),
    ("12", "loans-credit", "대출·신용·카드", "머니"),
    ("13", "insurance", "보험·연금", "머니"),
    ("14", "tax-benefits", "세금·정부지원", "머니"),
    ("15", "career-jobs", "직장·이직·연봉", "머니"),
    ("16", "side-business", "창업·부업·프리랜스", "머니"),
    ("17", "interior", "인테리어·홈스타일링", "홈"),
    ("18", "home-decor", "집들이·소품", "홈"),
    ("19", "appliances-review", "가전·생활용품 리뷰", "홈"),
    ("20", "cleaning-tips", "청소·살림팁", "홈"),
    ("21", "moving-repair", "이사·입주·집수리", "홈"),
    ("22", "solo-living", "원룸·자취·갓생", "홈"),
    ("23", "recipes", "요리·레시피", "푸드"),
    ("24", "restaurants", "맛집·먹방", "푸드"),
    ("25", "cafe-dessert", "카페·디저트", "푸드"),
    ("26", "delivery-convenience", "배달·편의점·간편식", "푸드"),
    ("27", "diet-meal", "다이어트 식단", "푸드"),
    ("28", "alcohol", "주류·와인·위스키", "푸드"),
    ("29", "fashion", "패션·코디", "스타일"),
    ("30", "makeup", "뷰티·메이크업", "스타일"),
    ("31", "skincare", "스킨케어", "스타일"),
    ("32", "hair-nail", "헤어·네일", "스타일"),
    ("33", "grooming-perfume", "향수·그루밍", "스타일"),
    ("34", "clinic-treatment", "피부과·시술·클리닉", "스타일"),
    ("35", "weight-loss", "다이어트·체중관리", "바디"),
    ("36", "fitness-home", "헬스·홈트", "바디"),
    ("37", "yoga-pilates", "요가·필라테스·스트레칭", "바디"),
    ("38", "running-outdoor", "러닝·등산·아웃도어", "바디"),
    ("39", "health-disease", "건강정보·질병", "바디"),
    ("40", "supplements", "영양제·건강식품", "바디"),
    ("41", "mental-health", "멘탈헬스·번아웃", "바디"),
    ("42", "pregnancy-birth", "임신·출산·태교", "패밀리"),
    ("43", "parenting", "육아·육아템", "패밀리"),
    ("44", "education-exam", "교육·학원·입시", "패밀리"),
    ("45", "family-generation", "부모·세대", "패밀리"),
    ("46", "pets", "반려동물", "패밀리"),
    ("47", "domestic-travel", "국내여행", "트립"),
    ("48", "international-travel", "해외여행", "트립"),
    ("49", "hotels-stay", "호텔·숙소·에어비앤비", "트립"),
    ("50", "camping-car", "캠핑·차박·글램핑", "트립"),
    ("51", "date-attractions", "테마파크·전시·데이트코스", "트립"),
    ("52", "photo-vlog", "사진·영상·브이로그", "플레이"),
    ("53", "craft-diy", "그림·공예·DIY", "플레이"),
    ("54", "music-performance", "음악·악기·공연", "플레이"),
    ("55", "books-novel", "독서·웹소설", "플레이"),
    ("56", "film-drama-ott", "영화·드라마·OTT", "플레이"),
    ("57", "entertainment-fandom", "연예·아이돌·팬", "플레이"),
    ("58", "comics-anime", "웹툰·만화·애니", "플레이"),
    ("59", "games-esports", "게임·e스포츠", "플레이"),
    ("60", "boardgame-collect", "보드게임·수집·피규어", "플레이"),
    ("61", "smartphone-tablet", "스마트폰·태블릿", "테크"),
    ("62", "pc-laptop-gear", "PC·노트북·주변기기", "테크"),
    ("63", "apps-services", "앱·서비스 리뷰", "테크"),
    ("64", "ai-tools", "AI·ChatGPT 활용", "테크"),
    ("65", "coding-beginner", "코딩·개발 입문", "테크"),
    ("66", "blog-sns-marketing", "블로그·SNS·마케팅", "테크"),
    ("67", "exam-cert-public", "시험·자격증·공무원", "인포"),
    ("68", "language-study-abroad", "어학·유학·이민", "인포"),
    ("69", "cars-driving", "자동차·운전·정비", "인포"),
    ("70", "legal-daily", "법·생활법률", "인포"),
    ("71", "news-opinion", "뉴스·시사·오피니언", "인포"),
    ("72", "local-neighborhood", "지역·로컬·동네", "인포"),
]

# l1_code -> list of (slug, name_ko)
L2_SEEDS: dict[str, list[tuple[str, str]]] = {
    "01": [
        ("diary", "일기·기록"),
        ("work-life", "직장인 일상"),
        ("weekend", "주말·휴일"),
        ("mindfulness", "마음챙김·명상"),
        ("seasonal", "계절·명절 일상"),
        ("home-cafe", "홈카페·취미생활"),
        ("gratitude", "감사·긍정"),
        ("life-review", "연말·월간 리뷰"),
    ],
    "02": [
        ("habits", "습관 만들기"),
        ("morning-routine", "모닝 루틴"),
        ("goals", "목표·플래너"),
        ("reading", "독서·글쓰기"),
        ("time-management", "시간·우선순위"),
        ("motivation", "동기부여"),
        ("digital-detox", "디톡스·집중"),
        ("life-tips", "생활 원칙"),
    ],
    "03": [
        ("notion", "노션·위키"),
        ("todo-apps", "할일·캘린더 앱"),
        ("automation", "자동화·매크로"),
        ("note-taking", "메모·PKM"),
        ("workspace", "책상·장비"),
        ("study-workflow", "공부·업무 흐름"),
        ("templates", "템플릿·세팅"),
        ("tools-review", "생산성 도구 리뷰"),
    ],
    "04": [
        ("declutter", "정리·버리기"),
        ("storage", "수납·정리함"),
        ("minimal-living", "미니멀 라이프"),
        ("closet", "옷장·의류 정리"),
        ("kitchen-organize", "주방 정리"),
        ("small-space", "좁은 집 정리"),
        ("capsule", "캡슐·소비 줄이기"),
        ("before-after", "정리 전후"),
    ],
    "05": [
        ("friends", "친구·지인"),
        ("workplace", "직장 관계"),
        ("boundaries", "거리두기·경계"),
        ("communication", "대화·표현"),
        ("conflict", "갈등·화해"),
        ("introvert", "내향·소규모"),
        ("networking", "네트워킹·모임"),
        ("etiquette", "매너·예절"),
    ],
    "06": [
        ("dating-tips", "연애 팁"),
        ("first-date", "첫 데이트"),
        ("apps", "소개팅·앱"),
        ("long-distance", "장거리 연애"),
        ("breakup", "이별·정리"),
        ("anniversary", "기념일·선물"),
        ("compatibility", "궁합·성향"),
        ("couple-life", "커플 일상"),
    ],
    "07": [
        ("preparation", "결혼 준비"),
        ("wedding-hall", "웨딩홀·예식"),
        ("studio-dress", "스드메·드레스"),
        ("honeymoon", "신혼여행"),
        ("gift-money", "예물·혼수"),
        ("invitation", "청첩·초대"),
        ("newlywed-home", "신혼집"),
        ("parents-meeting", "상견례"),
    ],
    "08": [
        ("divorce-process", "이혼·절차"),
        ("single-life", "싱글 라이프"),
        ("remarriage", "재혼"),
        ("co-parenting", "양육·공동"),
        ("emotional-healing", "회복·심리"),
        ("legal-basics", "이혼 법 기초"),
        ("dating-after", "재연애"),
        ("living-alone", "혼자 살기"),
    ],
    "09": [
        ("budget", "가계부·예산"),
        ("saving-challenge", "절약 챌린지"),
        ("frugal-living", "알뜰 생활"),
        ("coupons-deals", "쿠폰·할인"),
        ("subscriptions", "구독 정리"),
        ("emergency-fund", "비상금"),
        ("household-cost", "생활비·고정비"),
        ("money-mindset", "돈 마인드"),
    ],
    "10": [
        ("stocks-basics", "주식 기초"),
        ("etf-dividend", "ETF·배당"),
        ("portfolio", "포트폴리오"),
        ("us-market", "미국 주식"),
        ("analysis", "종목·재무 분석"),
        ("trading-tips", "매매·타이밍"),
        ("crypto-stock", "가상자산 주식"),
        ("beginner-guide", "초보 가이드"),
    ],
    "11": [
        ("jeonse-wolse", "전월세"),
        ("subscription-lottery", "청약"),
        ("apartment", "아파트·매매"),
        ("auction", "경매·공매"),
        ("commercial", "상가·사무실"),
        ("interior-cost", "인테리어 비용"),
        ("region-guide", "지역별 시세"),
        ("first-home", "내집마련"),
    ],
    "12": [
        ("credit-score", "신용점수"),
        ("cards-benefits", "카드 혜택"),
        ("loans-types", "대출 종류"),
        ("refinance", "대환·갈아타기"),
        ("student-loan", "학자금·청년"),
        ("mortgage", "주택담보"),
        ("overdue", "연체·채무"),
        ("interest-tips", "금리·상환"),
    ],
    "13": [
        ("health-insurance", "실손·건강"),
        ("car-insurance", "자동차"),
        ("life-insurance", "생명·종신"),
        ("cancer-care", "암·간병"),
        ("travel-insurance", "여행"),
        ("pension", "연금·노후"),
        ("claims", "보험금 청구"),
        ("comparison", "보험 비교"),
    ],
    "14": [
        ("year-end-tax", "연말정산"),
        ("deductions", "공제·환급"),
        ("youth-support", "청년·정부지원"),
        ("freelance-tax", "프리랜서 세금"),
        ("property-tax", "재산·취득세"),
        ("vat-business", "부가세·사업자"),
        ("filing-guide", "신고 가이드"),
        ("benefits-finder", "지원금 찾기"),
    ],
    "15": [
        ("job-search", "취업·이직"),
        ("resume-interview", "이력서·면접"),
        ("salary-negotiation", "연봉·협상"),
        ("workplace-culture", "회사 문화"),
        ("resignation", "퇴사·퇴직"),
        ("remote-hybrid", "재택·하이브리드"),
        ("career-change", "커리어 전환"),
        ("overtime-burnout", "야근·번아웃"),
    ],
    "16": [
        ("startup-basics", "창업 기초"),
        ("smartstore", "스마트스토어"),
        ("freelance-platform", "프리랜스 플랫폼"),
        ("coupang-blog", "쿠팡·블로그 수익"),
        ("youtube-creator", "유튜브·크리에이터"),
        ("business-registration", "사업자·세무"),
        ("side-hustle-ideas", "부업 아이디어"),
        ("one-person-shop", "1인 사업"),
    ],
    "17": [
        ("oneroom-style", "원룸 인테리어"),
        ("living-room", "거실"),
        ("bedroom", "침실"),
        ("kitchen-bath", "주방·욕실"),
        ("lighting", "조명"),
        ("floor-wall", "바닥·벽"),
        ("self-interior", "셀프 인테리어"),
        ("style-trends", "북유럽·모던 등"),
    ],
    "18": [
        ("tableware", "식기·테이블"),
        ("bedding", "침구·패브릭"),
        ("plants", "식물·화분"),
        ("art-frame", "그림·액자"),
        ("season-decor", "시즌 소품"),
        ("coupang-finds", "쿠팡·다이소템"),
        ("housewarming-gift", "집들이 선물"),
        ("scent-candle", "향·캔들"),
    ],
    "19": [
        ("kitchen-appliance", "주방가전"),
        ("cleaning-appliance", "청소가전"),
        ("air-season", "공기·계절가전"),
        ("tv-audio", "TV·음향"),
        ("small-gadgets", "생활 소형가전"),
        ("comparison", "가전 비교"),
        ("energy-saving", "전기·에너지"),
        ("purchase-guide", "구매 가이드"),
    ],
    "20": [
        ("daily-cleaning", "일상 청소"),
        ("deep-cleaning", "대청소"),
        ("kitchen-grease", "주방 기름때"),
        ("bathroom-mold", "욕실·곰팡이"),
        ("laundry", "세탁·빨래"),
        ("detergent-tools", "세제·도구"),
        ("organize-routine", "청소 루틴"),
        ("tips-hacks", "살림 꿀팁"),
    ],
    "21": [
        ("moving-checklist", "이사 체크리스트"),
        ("packing", "포장·업체"),
        ("move-in", "입주·청소"),
        ("repair-leak", "누수·하자"),
        ("paint-wallpaper", "도배·페인트"),
        ("appliance-install", "가전 설치"),
        ("contract-tips", "계약·견적"),
        ("diy-repair", "간단 수리 DIY"),
    ],
    "22": [
        ("oneroom-tips", "원룸 꿀팁"),
        ("rent-bills", "월세·관리비"),
        ("cooking-small", "자취 요리"),
        ("security-safety", "안전·보안"),
        ("neighbor-etiquette", "이웃·층간"),
        ("furniture-small", "좁은 집 가구"),
        ("routine", "자취 루틴"),
        ("cost-saving", "자취 절약"),
    ],
    "23": [
        ("korean-home", "한식·집밥"),
        ("airfryer", "에어프라이어"),
        ("meal-prep", "밀프렙·도시락"),
        ("baking", "베이킹"),
        ("dessert-home", "홈디저트"),
        ("side-dish", "반찬"),
        ("beginner-cook", "요리 초보"),
        ("ingredients", "재료·양념"),
    ],
    "24": [
        ("korean-food", "한식"),
        ("western", "양식·파스타"),
        ("japanese", "일식·스시"),
        ("chinese", "중식"),
        ("meat-bbq", "고기·BBQ"),
        ("solo-dining", "혼밥·혼술"),
        ("date-restaurant", "데이트 맛집"),
        ("local-famous", "지역 맛집"),
    ],
    "25": [
        ("cafe-review", "카페 후기"),
        ("bakery", "베이커리·빵"),
        ("dessert-cafe", "디저트 전문"),
        ("rooftop-view", "루프탑·뷰"),
        ("work-cafe", "작업·노트북 카페"),
        ("franchise", "프랜차이즈 커피"),
        ("home-cafe-recipe", "홈카페 레시피"),
        ("tea-noncoffee", "차·논커피"),
    ],
    "26": [
        ("delivery-apps", "배달앱·메뉴"),
        ("convenience-new", "편의점 신상"),
        ("frozen-meal", "간편식·냉동"),
        ("late-night", "야식"),
        ("office-lunch", "직장인 점심"),
        ("ramen-instant", "라면·인스턴트"),
        ("healthy-convenience", "건강 간편식"),
        ("review-ranking", "메뉴 랭킹"),
    ],
    "27": [
        ("keto-lowcarb", "저탄고지"),
        ("high-protein", "고단백"),
        ("intermittent", "간헐적 단식"),
        ("calorie-meal", "칼로리·식단표"),
        ("salad-bowl", "샐러드·볼"),
        ("diet-bento", "다이어트 도시락"),
        ("eating-out-diet", "외식 다이어트"),
        ("meal-plan-week", "주간 식단"),
    ],
    "28": [
        ("soju-beer", "소주·맥주"),
        ("wine-basics", "와인 입문"),
        ("whisky", "위스키"),
        ("cocktail-home", "홈칵테일"),
        ("pairing", "페어링"),
        ("sake", "사케·일본주"),
        ("hangover", "숙취·건강"),
        ("bar-review", "바·펍"),
    ],
    "29": [
        ("daily-look", "데일리룩"),
        ("office-look", "오피스룩"),
        ("seasonal", "시즌 코디"),
        ("mens-fashion", "남성 패션"),
        ("plus-size", "빅사이즈"),
        ("budget-brand", "가성비 브랜드"),
        ("luxury", "럭셔리·하이엔드"),
        ("capsule-wardrobe", "캡슐 옷장"),
    ],
    "30": [
        ("base-makeup", "베이스·파데"),
        ("lip", "립"),
        ("eye-makeup", "아이·섀도"),
        ("cushion-foundation", "쿠션·파운데이션"),
        ("beginner-makeup", "메이크업 초보"),
        ("tools", "브러시·퍼프"),
        ("tone-season", "톤·퍼스널컬러"),
        ("product-review", "색조 리뷰"),
    ],
    "31": [
        ("routine-am-pm", "스킨케어 루틴"),
        ("dry-skin", "건성"),
        ("oily-acne", "지성·여드름"),
        ("sensitive", "민감성"),
        ("anti-aging", "안티에이징"),
        ("ingredients", "성분·레티놀"),
        ("sunscreen", "선크림"),
        ("mask-ampoule", "마스크·앰플"),
    ],
    "32": [
        ("hair-color", "염색"),
        ("perm-style", "펌·스타일"),
        ("hair-care", "탈모·케어"),
        ("nail-art", "네일"),
        ("salon-review", "미용실 후기"),
        ("mens-hair", "남성 헤어"),
        ("home-care", "홈 헤어케어"),
        ("trend-style", "트렌드 헤어"),
    ],
    "33": [
        ("perfume", "향수"),
        ("mens-grooming", "남성 그루밍"),
        ("shaving-beard", "쉐이빙·수염"),
        ("skincare-men", "남성 스킨"),
        ("body-care", "바디케어"),
        ("deodorant", "데오·체취"),
        ("gift-set", "선물 세트"),
        ("niche-scent", "니치 향수"),
    ],
    "34": [
        ("laser-skin", "레이저"),
        ("botox-filler", "보톡스·필러"),
        ("acne-treatment", "여드름 치료"),
        ("clinic-choice", "병원 선택"),
        ("post-care", "시술 후 관리"),
        ("price-guide", "시술 비용"),
        ("skincare-after", "시술 후 홈케어"),
        ("side-effects", "부작용·주의"),
    ],
    "35": [
        ("diet-diary", "다이어트 일기"),
        ("plateau", "정체기"),
        ("workout-diet", "운동+식단"),
        ("body-fat", "체지방·인바디"),
        ("cheat-meal", "치팅·요요"),
        ("extreme-warning", "극단 다이어트 주의"),
        ("before-after", "전후"),
        ("goal-setting", "목표 체중"),
    ],
    "36": [
        ("gym-routine", "헬스 루틴"),
        ("home-workout", "홈트"),
        ("equipment", "덤벨·런닝머신"),
        ("muscle-split", "부위별 운동"),
        ("beginner-gym", "헬스 초보"),
        ("protein-workout", "단백질·보충"),
        ("form-tips", "자세·부상 예방"),
        ("body-recomposition", "체형 교정"),
    ],
    "37": [
        ("yoga-beginner", "요가 초보"),
        ("pilates", "필라테스"),
        ("stretching", "스트레칭"),
        ("posture", "자세·거북목"),
        ("flexibility", "유연성"),
        ("home-mat", "홈 요가"),
        ("class-review", "수업·스튜디오"),
        ("recovery", "회복·휴식"),
    ],
    "38": [
        ("running", "러닝·마라톤"),
        ("hiking", "등산"),
        ("cycling", "자전거"),
        ("camping-light", "가벼운 아웃도어"),
        ("gear-shoes", "장비·신발"),
        ("course-trail", "코스·트레일"),
        ("beginner-outdoor", "입문"),
        ("safety", "안전·준비물"),
    ],
    "39": [
        ("cold-fever", "감기·열"),
        ("chronic", "만성질환"),
        ("digestive", "소화·위장"),
        ("pain", "통증"),
        ("checkup", "검진"),
        ("hospital-guide", "병원·진료 가이드"),
        ("symptom-search", "증상 이해"),
        ("prevention", "예방·생활습관"),
    ],
    "40": [
        ("vitamins", "비타민"),
        ("omega-probiotics", "오메가·유산균"),
        ("protein-powder", "단백질 보충제"),
        ("joint-eye", "관절·눈 건강"),
        ("comparison", "영양제 비교"),
        ("timing-dose", "복용법·시간"),
        ("side-interaction", "부작용·상호작용"),
        ("fake-vs-real", "정품·선택"),
    ],
    "41": [
        ("anxiety", "불안"),
        ("depression-mood", "우울·기분"),
        ("burnout", "번아웃"),
        ("sleep-stress", "수면·스트레스"),
        ("counseling", "상담·치료"),
        ("meditation-app", "명상·앱"),
        ("work-life-balance", "워라밸"),
        ("self-care", "셀프케어"),
    ],
    "42": [
        ("pregnancy-week", "주차별 임신"),
        ("birth-prep", "출산 준비"),
        ("postpartum", "산후"),
        ("taegyo", "태교"),
        ("hospital-birth", "병원·분만"),
        ("baby-items-prenatal", "출산용품"),
        ("nutrition-pregnant", "임신 영양"),
        ("dad-partner", "예비 아빠·파트너"),
    ],
    "43": [
        ("newborn", "신생아·0세"),
        ("infant-toddler", "영·유아"),
        ("baby-products", "육아템"),
        ("baby-food", "이유식"),
        ("sleep-routine", "수면·놀이"),
        ("daycare", "어린이집·유치원"),
        ("discipline", "훈육·발달"),
        ("twin-multiple", "쌍둥이·다태아"),
    ],
    "44": [
        ("elementary", "초등"),
        ("middle-high", "중·고등"),
        ("suneung", "수능·입시"),
        ("academy-hagwon", "학원"),
        ("study-method", "공부법"),
        ("gifted-special", "영재·특목"),
        ("homeschool", "홈스쿨·대안"),
        ("parent-role", "부모 교육"),
    ],
    "45": [
        ("parents-gift", "부모님 선물"),
        ("filial-trip", "효도 여행"),
        ("aging-care", "노후·요양"),
        ("generation-gap", "세대 차이"),
        ("grandparenting", "조부모 역할"),
        ("family-event", "가족 행사"),
        ("communication-family", "가족 대화"),
        ("inheritance-basic", "상속 기초"),
    ],
    "46": [
        ("dog", "강아지"),
        ("cat", "고양이"),
        ("pet-food", "사료·간식"),
        ("pet-hospital", "동물병원"),
        ("training", "훈련·행동"),
        ("grooming-pet", "미용·목욕"),
        ("adoption", "입양"),
        ("exotic-small", "소동물"),
    ],
    "47": [
        ("seoul-capital", "수도권"),
        ("busan-gyeongnam", "부산·경남"),
        ("jeju", "제주"),
        ("gangwon", "강원"),
        ("jeolla", "전라"),
        ("chungcheong", "충청"),
        ("gyeongsang", "경상"),
        ("day-trip", "당일치기"),
    ],
    "48": [
        ("japan", "일본"),
        ("southeast-asia", "동남아"),
        ("europe", "유럽"),
        ("usa", "미국"),
        ("china-taiwan", "중국·대만"),
        ("australia", "호주"),
        ("visa-passport", "비자·여권"),
        ("itinerary-budget", "일정·예산"),
    ],
    "49": [
        ("hotel-review", "호텔 후기"),
        ("pension-stay", "펜션"),
        ("airbnb", "에어비앤비"),
        ("pool-spa", "풀·스파"),
        ("family-room", "가족룸"),
        ("budget-stay", "가성비 숙소"),
        ("booking-tips", "예약 팁"),
        ("luxury-resort", "리조트"),
    ],
    "50": [
        ("camping-gear", "캠핑 장비"),
        ("campsite", "캠핑장"),
        ("car-camping", "차박"),
        ("glamping", "글램핑"),
        ("backpacking", "백패킹"),
        ("fire-cooking", "불멍·캠핑 요리"),
        ("beginner-camping", "캠핑 입문"),
        ("season-weather", "계절·날씨"),
    ],
    "51": [
        ("theme-park", "놀이공원"),
        ("exhibition", "전시·박물관"),
        ("festival", "축제"),
        ("date-course", "데이트 코스"),
        ("photo-spot", "포토존"),
        ("indoor-date", "실내 데이트"),
        ("kids-outing", "아이와 나들이"),
        ("night-view", "야경"),
    ],
    "52": [
        ("camera-gear", "카메라·렌즈"),
        ("smartphone-photo", "스마트폰 촬영"),
        ("editing-app", "편집·앱"),
        ("vlog-youtube", "브이로그"),
        ("preset-filter", "프리셋·필터"),
        ("composition", "구도·색감"),
        ("lighting-shoot", "조명·촬영"),
        ("gear-review", "장비 리뷰"),
    ],
    "53": [
        ("drawing", "드로잉"),
        ("watercolor", "수채·페인트"),
        ("knit-craft", "뜨개·공예"),
        ("leather-wood", "가죽·목공"),
        ("upcycle", "업사이클"),
        ("handmade-gift", "핸드메이드"),
        ("calligraphy", "캘리·글씨"),
        ("resin-clay", "레진·클레이"),
    ],
    "54": [
        ("playlist", "플레이리스트"),
        ("concert-live", "콘서트"),
        ("instrument-learn", "악기 배우기"),
        ("kpop", "K-POP"),
        ("indie-music", "인디"),
        ("music-app", "음원·앱"),
        ("singing-karaoke", "노래·노래방"),
        ("album-review", "앨범 리뷰"),
    ],
    "55": [
        ("book-review", "도서 리뷰"),
        ("novel-fiction", "소설"),
        ("self-help-book", "자기계발서"),
        ("web-novel", "웹소설"),
        ("reading-habit", "독서 습관"),
        ("ebook-audio", "전자책·오디오"),
        ("book-club", "독서모임"),
        ("recommend-list", "추천 리스트"),
    ],
    "56": [
        ("netflix-ott", "넷플릭스·OTT"),
        ("drama-review", "드라마 리뷰"),
        ("movie-review", "영화 리뷰"),
        ("genre-pick", "장르별 추천"),
        ("ending-explained", "결말·해설"),
        ("actor-actress", "배우"),
        ("preview-new", "신작·예고"),
        ("watch-order", "정주행 순서"),
    ],
    "57": [
        ("idol", "아이돌"),
        ("comeback-stage", "컴백·무대"),
        ("concert-fan", "콘서트·팬"),
        ("goods-fandom", "굿즈·팬덤"),
        ("variety-star", "예능·셀럽"),
        ("dating-news", "연예 이슈"),
        ("chart-music-show", "차트·음방"),
        ("debut-rookie", "데뷔·루키"),
    ],
    "58": [
        ("webtoon", "웹툰"),
        ("manga", "만화"),
        ("anime", "애니"),
        ("recommend-series", "작품 추천"),
        ("character-goods", "캐릭터·굿즈"),
        ("cosplay", "코스프레"),
        ("platform-app", "플랫폼·앱"),
        ("genre-pick-anime", "장르 추천"),
    ],
    "59": [
        ("pc-games", "PC 게임"),
        ("mobile-games", "모바일 게임"),
        ("console", "콘솔"),
        ("lol-esports", "롤·e스포츠"),
        ("game-guide", "공략"),
        ("gear-peripheral", "게이밍 기어"),
        ("indie-steam", "인디·스팀"),
        ("patch-meta", "패치·메타"),
    ],
    "60": [
        ("boardgame", "보드게임"),
        ("lego-blocks", "레고·블록"),
        ("figure-collect", "피규어·수집"),
        ("tcg-card", "TCG·카드"),
        ("puzzle", "퍼즐"),
        ("tabletop-cafe", "보드게임 카페"),
        ("display", "진열·보관"),
        ("gift-hobby", "취미 선물"),
    ],
    "61": [
        ("iphone", "아이폰"),
        ("galaxy", "갤럭시"),
        ("tablet-ipad", "태블릿·아이패드"),
        ("compare-models", "기종 비교"),
        ("case-accessory", "케이스·액세"),
        ("battery-charge", "배터리·충전"),
        ("tips-tricks", "사용 팁"),
        ("launch-rumor", "신제품·루머"),
    ],
    "62": [
        ("laptop", "노트북"),
        ("desktop-pc", "데스크탑"),
        ("monitor", "모니터"),
        ("keyboard-mouse", "키보드·마우스"),
        ("gpu-cpu", "GPU·CPU"),
        ("mac-windows", "맥·윈도우"),
        ("upgrade-build", "조립·업그레이드"),
        ("review-spec", "스펙 리뷰"),
    ],
    "63": [
        ("productivity-apps", "생산성 앱"),
        ("finance-apps", "금융 앱"),
        ("delivery-life-apps", "생활 앱"),
        ("subscription-review", "구독 서비스"),
        ("app-comparison", "앱 비교"),
        ("privacy-security-app", "보안·개인정보"),
        ("new-app", "신규 앱"),
        ("tutorial-app", "앱 사용법"),
    ],
    "64": [
        ("chatgpt", "ChatGPT"),
        ("image-ai", "이미지 AI"),
        ("prompt-tips", "프롬프트"),
        ("work-automation", "업무 자동화"),
        ("coding-ai", "코딩 AI"),
        ("ai-tools-list", "AI 도구 모음"),
        ("ethics-copyright", "윤리·저작권"),
        ("claude-gemini-etc", "Claude·Gemini 등"),
    ],
    "65": [
        ("python", "Python"),
        ("javascript", "JavaScript"),
        ("web-basics", "웹 기초"),
        ("portfolio", "포트폴리오"),
        ("bootcamp", "부트캠프·강의"),
        ("github-git", "Git·GitHub"),
        ("career-dev", "개발 취업"),
        ("error-debug", "에러·디버깅"),
    ],
    "66": [
        ("blog-start", "블로그 시작"),
        ("seo-basics", "SEO"),
        ("instagram", "인스타그램"),
        ("youtube-grow", "유튜브 성장"),
        ("ads-sns", "광고·SNS"),
        ("analytics", "통계·분석"),
        ("monetization", "수익화"),
        ("branding", "브랜딩"),
    ],
    "67": [
        ("civil-exam", "공무원"),
        ("cert-it", "IT 자격증"),
        ("cert-finance", "금융 자격증"),
        ("study-schedule", "공부 계획"),
        ("past-exam", "기출·문제"),
        ("pass-review", "합격 후기"),
        ("firefighter-police", "소방·경찰"),
        ("professional-exam", "전문직 시험"),
    ],
    "68": [
        ("english", "영어"),
        ("japanese", "일본어"),
        ("toeic-opic", "토익·오픽"),
        ("study-abroad", "유학"),
        ("working-holiday", "워홀"),
        ("immigration-visa", "이민·비자"),
        ("language-school", "어학연수"),
        ("translation-tips", "번역·표현"),
    ],
    "69": [
        ("new-car", "신차"),
        ("used-car", "중고차"),
        ("electric-hybrid", "전기·하이브리드"),
        ("maintenance", "정비·소모품"),
        ("insurance-accident", "보험·사고"),
        ("driving-test", "면허·운전"),
        ("car-accessory", "용품·튜닝"),
        ("compare-models-car", "차종 비교"),
    ],
    "70": [
        ("lease-fraud", "전세사기"),
        ("labor-law", "근로·퇴직"),
        ("contract-basic", "계약 기초"),
        ("consumer-rights", "소비자"),
        ("fine-penalty", "과태료"),
        ("inheritance-gift", "상속·증여"),
        ("divorce-law", "이혼 법"),
        ("online-legal", "온라인 법률"),
    ],
    "71": [
        ("daily-news", "오늘 이슈"),
        ("politics-summary", "정치 요약"),
        ("economy-news", "경제"),
        ("international", "국제"),
        ("opinion-column", "칼럼·의견"),
        ("fact-check", "팩트체크"),
        ("election", "선거"),
        ("media-literacy", "미디어 리터러시"),
    ],
    "72": [
        ("neighborhood-guide", "동네 가이드"),
        ("local-restaurant", "동네 맛집"),
        ("market-festival", "시장·골목"),
        ("moving-area", "이사·지역 선택"),
        ("apartment-dong", "아파트·단지"),
        ("kids-facility", "공원·키즈"),
        ("parking-transport", "주차·교통"),
        ("local-news", "지역 소식"),
    ],
}


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)

    l1_path = DATA / "topics_l1.csv"
    with l1_path.open("w", encoding="utf-8") as f:
        f.write("l1_code,l1_slug,name_ko,mega_group,sort_order\n")
        for i, (code, slug, name_ko, mega) in enumerate(L1_LIST, start=1):
            f.write(f"{code},{slug},{name_ko},{mega},{i}\n")

    l2_path = DATA / "topics_l2.csv"
    with l2_path.open("w", encoding="utf-8") as f:
        f.write("l2_id,l1_code,l2_slug,name_ko,sort_order\n")
        for l1_code, _slug, _name, _mega in [
            (c, s, n, m) for c, s, n, m in L1_LIST
        ]:
            seeds = L2_SEEDS.get(l1_code, [])
            for j, (l2_slug, l2_name) in enumerate(seeds, start=1):
                l2_id = f"{l1_code}-{l2_slug}"
                f.write(f"{l2_id},{l1_code},{l2_slug},{l2_name},{j}\n")

    l1_count = len(L1_LIST)
    l2_count = sum(len(v) for v in L2_SEEDS.values())
    print(f"Wrote {l1_path} ({l1_count} L1)")
    print(f"Wrote {l2_path} ({l2_count} L2)")


if __name__ == "__main__":
    main()
